name: Cleanup Preview Deployment

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete Netlify Deploy Preview
        uses: nwtgck/actions-netlify@v2.1
        with:
          publish-dir: './dist'  # This won't be used for delete
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Cleanup preview deployment for closed PR #${{ github.event.pull_request.number }}"
          alias: pr-${{ github.event.pull_request.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5
        continue-on-error: true